### ISSUE TITLE
How to run this repo?

### ISSUE THREAD

**Issue by ruijunfeng** [benwilliamgraham/tree-sitter-llvm#5]
Hello, I noticed your project involves converting tree-sitter to LLVM. I'd like to inquire about how to run this project. Does it have the capability to convert all ASTs generated by tree-sitter into LLVM IR?

**Comment by benwilliamgraham** [comment]
Hi @ruijunfeng, thanks for your inquiry! This repo is meant to generate the AST from existing LLVM IR, meant to provide syntax highlighting for developers working with LLVM IR.

**Comment by ruijunfeng** [comment]
Thank you, @benwilliamgraham, for your prompt reply. I have a small question regarding how to use your repository. Is it possible for you to provide us with a small example to run this repository? For instance, given a Java code file to obtain a tree-sitter AST and then use that AST to generate an LLVM IR .ll file?

**Comment by benwilliamgraham** [comment]
Sorry, I think you might have it backward, this project does not convert an AST to LLVM IR, it converts LLVM IR in text format to a tree-sitter AST for syntax-highlighting purposes.
